"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var UsedCarPageData = (function () {
    function UsedCarPageData() {
        this.dataFlag = 0;
        this.allCount = 0;
        this.allOriginalData = [];
        this.allData = [];
        this.gzFilterData = [];
        this.yxFilterData = [];
        this.rrFilterData = [];
        this.sourceData = [];
        this.averagePrice = 0;
        this.lowPrice = 0;
        this.lowPriceData = null;
        this.gzlowPriceData = null;
        this.yxlowPriceData = null;
        this.rrlowPriceData = null;
        this.firstlowPriceData = null;
        this.gzCount = 0;
        this.yxCount = 0;
        this.rrCount = 0;
        this.monitorId = 0;
        this.loadingDisplay = 'block';
        this.monitorenoughDisplay = 'none';
        this.stopDisplay = 'none';
        this.updateMonitorDisplay = 'none';
        this.followDisplay = 'none';
        this.bottomType = 1;
        this.enoughBottom = false;
        this.dialogTitle = '';
        this.dialogText = '';
        this.dialogBtn = '';
        this.followText = '';
        this.followType = 1;
        this.followIndex = 0;
        this.mSelect = 1;
        this.isMtype = false;
        this.editFlag = false;
        this.selectAllFlag = false;
        this.singleEditFlag = false;
        this.startTimeName = '';
        this.taskTime = '';
        this.fee = 0;
        this.totalFee = 0;
        this.ddCoin = 0;
        this.bindPhone = false;
        this.bindPublic = false;
        this.sortType = 0;
        this.updateData = {};
        this.defalutData = {};
        this.scrollIng = false;
        this.scrollTop = 0;
        this.selectNum = 0;
        this.indexArr = [];
        this.advSort = 0;
    }
    return UsedCarPageData;
}());
exports.default = UsedCarPageData;
